### ISSUE TITLE
Improve page load performance

### ISSUE THREAD

**Issue by chasenlehara** [LBH3/lbh3.org#60]
## Issues

- [x] Only load Google Maps with the JS API
- [ ] [Replace moment-timezone with something smaller](https://github.com/LBH3/lbh3.org/issues/190)
- [ ] [Add data caching](https://github.com/LBH3/lbh3.org/issues/307)
- [ ] [Give bundles unique names so they can be cached](https://github.com/LBH3/lbh3.org/issues/308)

## Lighthouse

- [ ] bootup-time
- [ ] color-contrast
- [ ] critical-request-chains
- [ ] estimated-input-latency
- [ ] first-contentful-paint
- [ ] first-cpu-idle
- [ ] first-meaningful-paint
- [ ] font-display
- [ ] image-alt
- [ ] image-aspect-ratio
- [ ] interactive
- [x] link-name
- [ ] load-fast-enough-for-pwa
- [ ] mainthread-work-breakdown
- [ ] max-potential-fid
- [ ] offline-start-url
- [x] offscreen-images
- [ ] render-blocking-resources
- [x] robots-txt
- [ ] service-worker
- [ ] speed-index
- [ ] tap-targets
- [ ] time-to-first-byte
- [ ] unminified-css
- [ ] unused-css-rules
- [ ] uses-http2
- [ ] uses-long-cache-ttl
- [ ] uses-passive-event-listeners
- [x] uses-rel-preconnect
- [ ] uses-rel-preload
- [ ] uses-text-compression
- [ ] uses-webp-images
- [ ] works-offline

## Investigations

- [ ] Investigate if the FA brands font can be minimized to just the icons required
- [ ] Investigate techniques for not blocking rendering (async/defer)
- [ ] Investigate deploying assets to a CDN
- [ ] Investigate if less can be transpiled
- [ ] Investigate minifying HTML
