### ISSUE TITLE
2.2 launch checklist

### ISSUE THREAD

**Issue by chasenlehara** [LBH3/lbh3.org#89]
- [x] Get Dr. Strangeglove to sign into the website
- [x] Get Alouette to sign into the website
- [x] Get Yoko to sign into the website
- [x] Get 2005 Bored
- [x] Get full access to a recent copy of the FileMaker database
- [x] Figure out which of the hare counts should be used; prefer `hare_count_1` or `Hares No` because it’s calculated
- [x] Associate everyone’s user id with a hasher id in the website database
- [x] Fix importing patches and other fields that have multiple `<DATA>` entries
- [x] Fix the Mismanagement page
- [x] Write script for exporting headshot photos from FileMaker
- [x] Get 2014 Bored
- [x] Add all Bored history to the website database
- [x] Set up error and maintenance pages
- [x] Determine how Snooze email list is maintained
- [x] Copy the FileMaker database from Dropbox to the laptop
- [x] Export everything from FileMaker
- [x] Put the website in maintenance mode
- [x] Make a backup & download current Heroku database
- [x] Change which field is used for the hasher’s primary key
- [x] Run the database migration & import scripts
- [x] Upload headshots to S3
- [x] Update `hashers_id_seq` in the database
- [x] Confirm that the website looks ok
- [x] Export the database
- [x] Test making changes to the local database
- [x] Upload updated database to Heroku
- [x] Merge branch to `master`
- [x] Confirm successful deploy
- [x] Take the website out of maintenance mode
- [x] Notify Bored members of updated site
- [x] Confirm Dr. Strangeglove can access protected parts of the website
- [x] Confirm Yoko can access protected parts of the website
